component_depth: 1

languages:
- csharp
- javascript
- typescript

exclude:
- /EmbyStat.Common/Models/.*
- /EmbyStat.Controllers/ViewModels/.*
- /EmbyStat.Common/Models/.*   
- /EmbyStat.Repositories/DatabaseInitializer.cs
- /EmbyStat.Repositories/Migrations/.*
- /EmbyStat.Common/Helpers/.*
- /EmbyStat.Common/Converters/.*
- /EmbyStat.Api/EmbyClient/.*
- /EmbyStat.Web/ClientApp/.*
- /EmbyStat.Common/Constants.cs
- /EmbyStat.DI/DIExtentions.cs
- /Tests.Unit/.*
- /Tests.Integration/.*