jobs:
- job: docker_container
  dependsOn: main_build
  displayName: 'Copy Docker files'
  pool:
    name: Hosted Windows 2019 with VS2019
  variables:
    GitVersion.AssemblySemVer: $[ dependencies.main_build.outputs['setAssemblySemVer.AssemblySemVer'] ]
    GitVersion.SemVer: $[ dependencies.main_build.outputs['setSemVer.SemVer'] ]
  steps:
  - template: '../templates/update.version.yml'

  - task: PowerShell@2
    displayName: 'Copy Docker files'
    inputs:
      targetType: filePath
      filePath: ./builds/docker-containers/dockerfiles.ps1

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Docker files'
    inputs:
      PathtoPublish: publish
      ArtifactName: 'EmbyStat-dockerfiles'